#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9000
logging.level:
  org.springframework.security: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:authz.pub
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true